---
name: Métodos y estado
locale: es
type: learning
beta: false
teacher_info: ''
language: wollok
id_format: '%05d'
order:
- 22
- 18
- 3
- 23
- 4
- 5
- 25
- 24
- 20
- 21
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
