---
name: Objetos y mensajes
locale: es
type: learning
beta: false
teacher_info: ''
language: wollok
id_format: '%05d'
order:
- 1
- 22
- 19
- 23
- 24
- 25
- 26
- 29
- 30
- 27
- 28
- 18
- 2
- 3
- 4
- 5
- 21
- 20
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 31
