---
tags: []
layout: editor_right
type: playground
extra_visible: true
language: 
teacher_info: |-
  Acá la idea es mostrar que todo (hasta acá) se resuelve en términos de objetos y mensajes:

   * los operadores son mensajes
   * los atributos sólo se pueden acceder mediante mensajes
manual_evaluation: false
